package com.unnormal.data.entity;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;

/**
 * Created by Vazgen on 08/02/2016.
 */
@Entity
@Table(name = "users")
public class UserEntity implements Serializable {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @NotNull
    private String email;

    @NotNull
    private String name;

    // Public methods

    public UserEntity() {
    }

    public UserEntity(long id) {
        this.id = id;
    }

    public UserEntity(String email, String name) {
        this.email = email;
        this.name = name;
    }
}

